
package ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ProductSEI", targetNamespace = "http://ServerSide/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ProductSEI {


    /**
     * 
     * @return
     *     returns ws.ProductArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ServerSide/ProductSEI/getProductListRequest", output = "http://ServerSide/ProductSEI/getProductListResponse")
    public ProductArray getProductList();

    /**
     * 
     * @param arg0
     * @return
     *     returns ws.Product
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ServerSide/ProductSEI/getProductRequest", output = "http://ServerSide/ProductSEI/getProductResponse")
    public Product getProduct(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ServerSide/ProductSEI/orderRequest", output = "http://ServerSide/ProductSEI/orderResponse")
    public boolean order(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0,
        @WebParam(name = "arg1", partName = "arg1")
        int arg1);

}
