
package ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ProductIMPL", targetNamespace = "http://ServerSide/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ProductIMPL {


    /**
     * 
     * @return
     *     returns ws.ProductArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ServerSide/ProductIMPL/getProductListRequest", output = "http://ServerSide/ProductIMPL/getProductListResponse")
    public ProductArray getProductList();

    /**
     * 
     * @param arg0
     * @return
     *     returns ws.Product
     * @throws SOAPException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ServerSide/ProductIMPL/getProductRequest", output = "http://ServerSide/ProductIMPL/getProductResponse", fault = {
        @FaultAction(className = SOAPException_Exception.class, value = "http://ServerSide/ProductIMPL/getProduct/Fault/SOAPException")
    })
    public Product getProduct(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0)
        throws SOAPException_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     * @throws SOAPException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ServerSide/ProductIMPL/orderRequest", output = "http://ServerSide/ProductIMPL/orderResponse", fault = {
        @FaultAction(className = SOAPException_Exception.class, value = "http://ServerSide/ProductIMPL/order/Fault/SOAPException")
    })
    public boolean order(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0,
        @WebParam(name = "arg1", partName = "arg1")
        int arg1)
        throws SOAPException_Exception
    ;

}
